### ISSUE TITLE
+ Bio Industries mod = Crash

### ISSUE THREAD

**Issue by safronov-nikolai** [sparr/factorio-mod-wreckage-pollution#4]
The "Bio Industries" mod has liquids (nitrogen) that crash the factorio-mod-wreckage-pollution mod.

The mod Wreckage Pollution caused a non-recoverable error.
Please report this error to the mod author.

Error while running event wreckage-pollution::on_pre_player_mined_item (ID 11)
Unknown entity name: chemical-spill-nitrogen-small
stack traceback:
wreckage-pollution/control.lua:110: in function 'fluidSpill'
wreckage-pollution/control.lua:160: in function <wreckage-pollution/control.lua:159>
stack traceback:
[C]: in function 'create_entity'
wreckage-pollution/control.lua:110: in function 'fluidSpill'
wreckage-pollution/control.lua:160: in function <wreckage-pollution/control.lua:159>

**Comment by sparr** [comment]
This is because Bio Industries is creating new items (fluids, in particular) in their data-final-fixes.lua which they should not be doing. You'll need to convince them to move the item definition to an appropriate earlier stage of the data lifecycle.

**Comment by sparr** [comment]
https://mods.factorio.com/mod/Bio_Industries/discussion/5f31f7ba75ce84907a09f877
